######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 6 01:02:58 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += mainwindow.cpp wmanager.cpp
RESOURCES += application.qrc
LIBS+= /usr/lib/libpolkit-qt-gui-1.so.1.103.0 /usr/lib/libpolkit-qt-core-1.so.1
