######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 6 00:48:25 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test.cpp
