######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 10 19:33:37 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
