######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 10 22:57:00 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += clogger.cpp mainwindow.cpp
RESOURCES += application.qrc
