######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 6 18:35:38 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += PkExample.h PkExampleHelper.h
FORMS += PkExample.ui
SOURCES += main.cpp mainHelper.cpp PkExample.cpp PkExampleHelper.cpp
